control-rails: shaka-perf servers run-overmind-command control "CUSTOM_DOMAIN=localhost PUMA_ROOT=. ./twin-servers/start-rails"
control-renderer: shaka-perf servers run-overmind-command control "sh ./twin-servers/start-renderer"
experiment-rails: shaka-perf servers run-overmind-command experiment "CUSTOM_DOMAIN=localhost PUMA_ROOT=. ./twin-servers/start-rails"
experiment-renderer: shaka-perf servers run-overmind-command experiment "sh ./twin-servers/start-renderer"
notify-control-server-started: shaka-perf servers notify-server-started control
notify-experiment-server-started: shaka-perf servers notify-server-started experiment
