name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    if: ${{ github.repository != 'shakacode/react-on-rails-demo-gumroad-rsc' }}
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - run: npm ci

      - uses: ruby/setup-ruby@v1.319.0
        with:
          bundler-cache: true

      - run: npm run setup

      - name: Run TSC
        run: npx tsc

      - name: Run eslint
        run: npx eslint --fix --max-warnings 0

      - name: Run prettier
        run: npx prettier --write '**/*.{css,scss,md,json}'

      - run: bundle exec rubocop -a

      - name: Run SVGO
        run: npx svgo --multipass app/assets/**/*.svg

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
